// 'use client';

import React from "react";
// import type { Metadata } from "next";
import { KeycloakProvider } from "@/lib/auth";
import { DashboardProvider } from "@/components/Dashboard";

// export const metadata: Metadata = {
//     title: "Editor de página - BONDE",
//     description: "Generated by create next app"
// }

export default async function EditorLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <KeycloakProvider>
            {children}
        </KeycloakProvider>
    )
}